name = input("Enter your name: ") 
job = input("Enter your job: ")
id = input("Enter your ID: ")
telephone = input("Enter your telephone number: ")
salary = input("Enter your salary: ")
payscale = input("Enter your pay scale: ")
print()
print(name)
print(job)
print(id)
print(telephone)
print(salary)
print(payscale)
print('name') 